c4Final/webshop/cart/urls.py
from django.urls import path
from .views import cart_detail, cart_add, cart_remove, order, created_order

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name = 'cart_detail'),
    path('add/<int:product_id>/', cart_add, name = 'cart_add'),
    path('remove/<int:product_id>/', cart_remove, name = 'cart_remove'),
    path('order/', order, name = 'order'),
    path('order/orderconf/', created_order , name = 'orderconf'),
]

c4Final/webshop/main/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('search/', search_product, name='search_product'),
    path('<str:category_name>/<int:pk>/', product_detail, name='product'),
    path('<str:category_name>/<int:pk>/all_reviews/', all_reviews, name='all_reviews'),
    # path('<str:category_name>/<int:pk>/<slug:product_name>/add_review/', add_review, name='add_review'),
    path('<str:category_name>/', category_view, name='category'),
]

c4Final/webshop/webshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls'), name='cart'), 
    path('', include('main.urls')),
    path('auth/', include('regLog.urls'), name='auth'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

c4Final/webshop/main/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from autoslug import AutoSlugField

# Create your models here.

class Category(models.Model):

    name = models.CharField(max_length=100, unique=True)

    class Meta:
        verbose_name_plural = "categories"
        
    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    description = models.TextField(blank = True)
    category = models.ForeignKey(to=Category, on_delete=models.SET_NULL, null=True, blank=True)
    
    def __str__(self):
        return f"{self.name} {str(self.id)}"
    

class Image(models.Model):
    image = models.ImageField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)


class Stats(models.Model):
    name = models.CharField(max_length=255)
    value = models.CharField(max_length=255)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)


class Review(models.Model):
    RATING_CHOICES = (
        (5, '5'),
        (4, '4'),
        (3, '3'),
        (2, '2'),
        (1, '1'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='review', on_delete=models.CASCADE,null=True)
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='Publication Date')
    rating = models.IntegerField(choices=RATING_CHOICES, default=None, null=True, blank=True)
    text = models.TextField()
    advantages = models.TextField(blank=True)
    disadvantages = models.TextField(blank=True)

    def __str__(self):
         return f"{self.user.username} - {self.pub_date.strftime('%Y-%m-%d %H:%M:%S')} - {self.product}"


class Cart(models.Model):
    products = models.ManyToManyField('Product')
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    cookie_id = models.CharField(max_length=32, null=True, blank=True)

c4Final/webshop/main/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'text', 'advantages', 'disadvantages']
        widgets = {
            'text': forms.Textarea(attrs={'rows': 5}),
        }
        labels = {
            'rating': 'Your Rating', 
        }
        required = {
            'rating': True,  
            'text': False,  
            'advantages': False,
            'disadvantages': False,
        }

c4Final/webshop/main/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import ReviewForm
from django.core.paginator import Paginator, EmptyPage
from django.views.generic import TemplateView, ListView
from django.db.models import Q
from .models import *
from cart.forms import CartAddProductForm
from math import ceil
from random import sample

from django.core.paginator import Paginator
# Create your views here.

def get_recently_viewed_products(request):
    recently_viewed_qs = Product.objects.filter(pk__in=request.session.get("recently_viewed", []))
    print("qs", recently_viewed_qs)
    return sorted(recently_viewed_qs, key=lambda x: request.session["recently_viewed"].index(x.id))

def home(request):
    recently_viewed_qs = get_recently_viewed_products(request)
    all_products = Product.objects.all()
    random_five_products = sample(list(all_products), min(5, len(all_products)))
    return render(request, 'main/home.html', {'products':random_five_products, 'recently_viewed': recently_viewed_qs})

def recently_viewed(request, product_id):
    if not "recently_viewed" in request.session:
        request.session["recently_viewed"] = []
        request.session["recently_viewed"].append(product_id)
    else:
        if product_id in request.session["recently_viewed"]:
            request.session["recently_viewed"].remove(product_id)
        request.session["recently_viewed"].insert(0, product_id)
        if len(request.session["recently_viewed"]) > 5:
            request.session["recently_viewed"].pop()
    request.session.modified =True

def product_detail(request, category_name, pk):
    product = get_object_or_404(Product, category__name=category_name, pk=pk)
    images = Image.objects.filter(product=product)
    stats = Stats.objects.filter(product=product)
    reviews = Review.objects.filter(product=product)
    cart_product_form =CartAddProductForm()

    recently_viewed(request, pk)
    recently_viewed_qs = get_recently_viewed_products(request)

    if request.user.is_authenticated:
        if request.method == 'POST':
            form = ReviewForm(request.POST)
            
            if form.is_valid():
            
                review = form.save(commit=False)
                review.product = product
                review.save()
        else:
            form = ReviewForm()
    elif not request.user.is_authenticated:
        form = ReviewForm()

    return render(request, 'main/product_page.html', {'product': product, 'images': images, \
                                                 'stats': stats, 'reviews': reviews, 'user': request.user ,
                                                 'cart_product_form': cart_product_form, \
                                                 'recently_viewed': recently_viewed_qs, 'form': form})

def get_categories():
    categories = Category.objects.all()
    return {'categories': categories}

def category_view(request, category_name):
    category = get_object_or_404(Category, name=category_name)
    products_by_category = Product.objects.filter(category=category)
    page = request.GET.get('page')
    if not page:
        page = 1
    else:
        page = int(page)

    count_on_one_page = 2
    count_pages = range(1, ceil(len(products_by_category) / count_on_one_page) + 1)
    return render(request, 'main/category.html', {'products_by_category':products_by_category[count_on_one_page * (page - 1):count_on_one_page * page],
                                                         'count_pages': count_pages, 'category': category,
                                                        })

    
def search_product(request):
    queryset = Product.objects.all()
    query = request.GET.get("q")
    if query:
        queryset = queryset.filter(
            Q(name__icontains=query) 
        ).distinct()

        paginator = Paginator(queryset, 2) 
        page = request.GET.get('page', 1)

        try:
            current_page = paginator.page(page)
        except EmptyPage:
            current_page = paginator.page(paginator.num_pages)

        context = {
            "queryset": current_page,
            'count_pages': paginator.page_range,
            'q': query
        }
        return render(request, 'main/search_product.html', context)
    return render(request, 'main/search_product.html')


def all_reviews(request, category_name, pk):
    product = get_object_or_404(Product, category__name=category_name, pk=pk)
    reviews = Review.objects.filter(product=product)
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = ReviewForm(request.POST)
            print("xddsds")
            if form.is_valid():
                review = form.save(commit=False)
                review.product = product
                review.save()
        else:
            form = ReviewForm()
    elif not request.user.is_authenticated:
        form = ReviewForm()
    return render(request, 'main/all_reviews.html', {'product': product, 'reviews': reviews, 'form': form})

c4Final/webshop/main/templates/main/add_review.html
{% extends 'main/base.html' %}

{% block content %}
  
    <h2>Add a Review</h2>
    <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Submit Review</button>
    </form>
    <p>Please log in to add a review.</p>

{% endblock %}

c4Final/webshop/main/templates/main/all_reviews.html
{% extends 'main/base.html' %}


{% block content %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>All Reviews for {{ product.name }}</title>
</head>
<body>
    <h1>All Reviews for {{ product.name }}</h1>
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" style="background-color:#906ab6; border-color: #432152;">
        Add Review
    </button>
    {% for review in reviews|slice:"::-1"|slice:":5" %}
    <div style="background-color: #E0AED0; padding: 10px; margin-bottom: 10px;">
      <p>{{ review.user.username }}: 
          {% if review.text %}
              {{ review.text }}
          {% endif %}
      </p>
      <p>Rating: {{ review.rating }}</p>
      <p>
          {% if review.advantages %}
              Advantages: {{ review.advantages }}
          {% endif %}
      </p>
      <p>
          {% if review.disadvantages %}
              Disadvantages: {{ review.disadvantages }}
          {% endif %}
      </p>
    </div>
{% endfor %}


</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Write a Review</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {% if user.is_authenticated %}
                    <p>You are logged in. Write your review:</p>
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary" style="background-color:#906ab6; border-color: #432152;">Submit Review</button>
                    </form>
                {% else %}
                    <p>You are not logged in. Please log in to write a review.</p>
                    <form method="POST" action="{% url 'login' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">Log In</button>
                    </form>
                {% endif %}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" style="background-color:#906ab6; border-color: #432152;">Close</button>
            </div>
        </div>
    </div>
</div>
</div>
</html>
{% endblock %}

c4Final/webshop/main/templates/main/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <style>
      body {
        background-color: #FFE5E5;
      }
    </style>
  </head>
  <body>
    {% include 'main/navbar.html' with categories=categories %}
    {% block content %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>

  </body>
</html>

c4Final/webshop/main/templates/main/category.html
{% extends 'main/base.html' %}

{% block content %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Home</title>
    </head>
    <body>

        <h1>{{ category.name }}</h1>

        {% for product in products_by_category %}
        <div class="product">
            <a href="{% url 'product' product.category product.id  %}">
                {% include 'main/product.html' with product=product %}
            </a>
        </div>
        {% endfor %}
        {% for page in count_pages %}
            <a href="?page={{ page }}" class="page">{{ page }}</a>
        {% endfor %}


    </body>
    </html>
{% endblock %}

c4Final/webshop/main/templates/main/home.html
{% extends 'main/base.html' %}

{% block content %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Home</title>
    </head>
    <body>
        <h1>Products</h1>
        <div class="product-container">
            {% for product in products %}
                <div class="product">
                    <a href="{% url 'product' product.category product.id %}">
                        {% include 'main/product.html' with product=product %}
                    </a>
                </div>
            {% endfor %}
        </div>
        <div class="recently">
        <h1>Recently viewed</h1>
            {% if recently_viewed %}
            <ul>
                {% for product in recently_viewed %}
                    <li>
                        <a href="{% url 'product' product.category product.id %}" style="color: #E0AED0; font-size: 20px; cursor: pointer; font-weight: bold;"> 
                            <img src="{{ product.image_set.first.image.url }}" alt="{{ product.name }}" width="100">
                            <strong>{{ product.name }} ({{ product.pk }})</strong>
                        </a>
                    </li>
                {% endfor %}
            </ul>
            {% else %}
                <p>No recently viewed products.</p>
            {% endif %}
        </div>  
    </body>
    </html>
{% endblock %}

c4Final/webshop/main/templates/main/navbar.html
{% load static %}

<head>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<nav class="navbar navbar-expand-lg" style='background-color: #906ab6'>
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}" style="color: #FFE5E5; font-size: 25px; font-weight: bold;">MyShop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link style-css dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/Smartphones">Smartphones</a></li>
            <li><a class="dropdown-item" href="/Camera">Camera</a></li> 
            
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search" method="GET" action="{% url 'search_product' %}" onsubmit="return validateSearchForm()">
        <div class="input-group">
          <input class="form-control search-bg" type="search" placeholder="Type here..." aria-label="Search" name="q">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </div>
      </form>
      
      <script>
        function validateSearchForm() {
          var searchInput = document.querySelector('input[name="q"]');
          return searchInput.value.trim() !== '';
        }
      </script>
      
      <form class="d-flex">
        <a href="{% url 'cart:cart_detail'%}" class="btn position-relative text-decoration-none">
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" class="bi bi-cart3" viewBox="0 0 16 16">
                <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5M3.102 4l.84 4.479 9.144-.459L13.89 4zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4m7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4m-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2m7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2"/>
            </svg>
            {% with total_items=cart|length %}
                <span class="badge bg-custom-color text-white position-absolute top-0 end-0 rounded-circle">
                  {{ total_items }}
                </span>
            {% endwith %}
          </a>
    </form>
    
    
    
      
      
      <ul class="navbar-nav mr-auto">
        {% if not user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'signup' %}">Signup</a>
        </li>
        {% else %}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" style="color: #FFE5E5; font-size: 15px;" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
              </svg>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <span class="dropdown-item-text">{{ user.username }}</span>
                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
            </div>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

c4Final/webshop/main/templates/main/product.html
<div class="product_view">
    <img src="{{ product.image_set.first.image.url }}" alt="{{ product.name }}" width="300">
    <h2>{{ product.name }}</h2>
    <p>Price: ${{ product.price }}</p>
</div>

c4Final/webshop/main/templates/main/product_page.html
{% extends 'main/base.html' %}


{% block content %}
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{ product.name }}</title>
</head>
<main class="container">
 
    <div class="left-column">
      <div id="carouselExampleIndicators" class="carousel slide">
        <div class="carousel-indicators">
          {% for image in images %}
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %} aria-label="Slide {{ forloop.counter }}"></button>
          {% endfor %}
        </div>
        <div class="carousel-inner">
          {% for image in images %}
            <div class="carousel-item {% if forloop.first %}active{% endif %} product-image">
              <img src="{{ image.image.url }}" class="d-block w-1" alt="{{ product.name }}">
            </div>
          {% endfor %}
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
        <span style="color: #E0AED0; font-size: 40px; cursor: pointer; font-weight: bold;" onclick="window.location='{% url 'all_reviews' product.category product.id  %}'">Reviews</span>
        {% for review in reviews|slice:"::-1"|slice:":5" %}
                <div style="background-color: #E0AED0; padding: 10px; margin-bottom: 10px;">
                  <p>{{ review.user.username }}: 
                      {% if review.text %}
                          {{ review.text }}
                      {% endif %}
                  </p>
                  <p>Rating: {{ review.rating }}</p>
                  <p>
                      {% if review.advantages %}
                          Advantages: {{ review.advantages }}
                      {% endif %}
                  </p>
                  <p>
                      {% if review.disadvantages %}
                          Disadvantages: {{ review.disadvantages }}
                      {% endif %}
                  </p>
                </div>
        {% endfor %}
      
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" style="background-color:#906ab6; border-color: #432152;">
          Add Review
        </button>
      </div>

      
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
              <div class="modal-content">
                  <div class="modal-header">
                      <h1 class="modal-title fs-5" id="exampleModalLabel">Write a Review</h1>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                      {% if user.is_authenticated %}
                          <p>You are logged in. Write your review:</p>
                          <form method="POST">
                              {% csrf_token %}
                              {{ form.as_p }}
                              <button type="submit" class="btn btn-primary" style="background-color:#906ab6; border-color: #432152;">Submit Review</button>
                          </form>
                      {% else %}
                          <p>You are not logged in. Please log in to write a review.</p>
                          <form method="POST" action="{% url 'login' %}">
                              {% csrf_token %}
                              <button type="submit" class="btn btn-primary">Log In</button>
                          </form>
                      {% endif %}
                  </div>
                  <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" style="background-color:#906ab6; border-color: #432152;">Close</button>
                  </div>
              </div>
          </div>
      </div>
    </div>
    
   
    <div class="right-column">
      <div class="product-description">
        <h1 class="h_name" style="font-size: 35px;" >{{ product.name }}</h1>
      </div>
      <p class="p_price">Price: {{ product.price }}$</p>
      <form action="{% url 'cart:cart_add' product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Add to cart" class="add_to">
      </form>
      <div class="description" style="font-size: 20px;">
        <p >Description: {{ product.description }}</p>
      </div>
      <div class="characteristics">
        <h2>Characteristics</h2>
        <ul>
            {% for stat in stats %}
                <li>{{ stat.name }}: {{ stat.value }}</li>
            {% endfor %}
        </ul>
      </div>
    </div>
  </main>
{% endblock %}

c4Final/webshop/main/templates/main/search_product.html
{% extends 'main/base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
{% block content %}
    {% csrf_token %}
    <h1>Result of search: {{ q }}</h1>
    <br/>

    {% if queryset %}
        {% for product in queryset %}
            <a href="{% url 'product' product.category product.id%}">
                {% include 'main/product.html' with product=product %}
            </a><br/>
        {% endfor %}
    {% else %}
        <p>No products found for your search.</p>
    {% endif %}

    {% for page_num in count_pages %}
        <a href="?page={{ page_num }}&q={{ q }}" class="page">{{ page_num }}</a>
    {% endfor %}
{% endblock %}  
</body>
</html>