c4Final/webshop/cart/urls.py
from django.urls import path
from .views import cart_detail, cart_add, cart_remove, order, created_order

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name = 'cart_detail'),
    path('add/<int:product_id>/', cart_add, name = 'cart_add'),
    path('remove/<int:product_id>/', cart_remove, name = 'cart_remove'),
    path('order/', order, name = 'order'),
    path('order/orderconf/', created_order , name = 'orderconf'),
]

c4Final/webshop/webshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls'), name='cart'), 
    path('', include('main.urls')),
    path('auth/', include('regLog.urls'), name='auth'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

c4Final/webshop/cart/models.py
from django.db import models

# Create your models here.
class Order(models.Model):

    email = models.CharField(max_length=254)
    name = models.CharField(max_length=254)
    order_number = models.IntegerField(unique=True, default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Orders"
        
    def __str__(self):
        return self.name 

c4Final/webshop/main/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from autoslug import AutoSlugField

# Create your models here.

class Category(models.Model):

    name = models.CharField(max_length=100, unique=True)

    class Meta:
        verbose_name_plural = "categories"
        
    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    description = models.TextField(blank = True)
    category = models.ForeignKey(to=Category, on_delete=models.SET_NULL, null=True, blank=True)
    
    def __str__(self):
        return f"{self.name} {str(self.id)}"
    

class Image(models.Model):
    image = models.ImageField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)


class Stats(models.Model):
    name = models.CharField(max_length=255)
    value = models.CharField(max_length=255)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)


class Review(models.Model):
    RATING_CHOICES = (
        (5, '5'),
        (4, '4'),
        (3, '3'),
        (2, '2'),
        (1, '1'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='review', on_delete=models.CASCADE,null=True)
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='Publication Date')
    rating = models.IntegerField(choices=RATING_CHOICES, default=None, null=True, blank=True)
    text = models.TextField()
    advantages = models.TextField(blank=True)
    disadvantages = models.TextField(blank=True)

    def __str__(self):
         return f"{self.user.username} - {self.pub_date.strftime('%Y-%m-%d %H:%M:%S')} - {self.product}"


class Cart(models.Model):
    products = models.ManyToManyField('Product')
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    cookie_id = models.CharField(max_length=32, null=True, blank=True)

c4Final/webshop/cart/forms.py
from django import forms
from .models import Order


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [ 'email', 'name']
    order_number = forms.IntegerField(required=False, widget=forms.HiddenInput())

c4Final/webshop/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from .cart import Cart
from main.models import Product
from .forms import CartAddProductForm, OrderForm
from .models import Order
import random
from webshop.settings import MONOBANK_TOKEN
import requests


# Create your views here.
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id) 
    form =CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id) 
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial=
                                                          {'quantity':item['quantity'],
                                                           'override':True})
    return render(request, 'cart/detail.html', {'cart': cart})


def order(request):
    return render(request, 'cart/order_page.html')

def monobank_payment():
    headers = {
    'X-Token': MONOBANK_TOKEN,
    }

    redirect_url = 'http://127.0.0.1:8000/cart/order/orderconf/'

    res = requests.post('https://api.monobank.ua/api/merchant/invoice/create', headers=headers, json = {
        'amount': 10000,
        'ccy': 840,
        'redirectUrl': redirect_url,
    })

    print(res.text)

    if res.status_code == 200:
    
        response_json = res.json()
    
        page_url = response_json.get('pageUrl', None)

    return page_url

    
def created_order(request):
    
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            random_order_number = random.randint(1000, 9999)
            form.instance.order_number = random_order_number
            form.save()

            request.session['order_number'] = random_order_number
            print('order created')
            order_number = request.session.get('order_number')

            page_url = monobank_payment()
            return redirect(page_url)

    else:
        form = OrderForm()
        
    return render(request, 'cart/order_confirm.html', {'form': form})

c4Final/webshop/cart/templates/cart/detail.html
{% extends 'main/base.html' %}
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

{% block content %}
    <div class="col-lg-12 col-md-12 col-12">
    <h3 class="display-5 mb-2 text-center">Shopping Cart</h3>
    {% if cart %}
        <p class="mb-5 text-center">
            <i class="text-info font-weight-bold"></i></p>
            <table class="table table-primary table-striped">
            <thead>
                <tr>
                    <th style="width:30%">Product</th>
                    <th style="width:12%">Price per unit</th>
                    <th style="width:10%">Quantity</th>
                    <th style="width:12%">Price</th>
                    <th style="width:12%">Remove</th>
                    
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                    {% with product=item.product %}
                        <tr>
                            <td data-th="Product">
                                <div class="row">
                                    <div class="col-md-3 text-left">
                                        <img src="{% if product.image_set.first.image %}{{ product.image_set.first.image.url }}{% else %}{% static 'path/to/placeholder_image.jpg' %}{% endif %}" width="100" height="100">
                                    </div>
                                    <div class="col-md-9 text-left mt-sm-2">
                                        <h4>{{ product.name }}</h4>
                                    </div>
                                </div>
                            </td>
                            <td class="num">{{ item.price }}$</td>  
                            <td data-th="Quantity">
                                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.override }}
                                    <input type="submit" value="Update">
                                    {% csrf_token %}
                                </form>
                            </td>
                            <td class="num">{{ item.total_price }}$</td>
                            <td>
                                <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                                    <input type="submit" value="Remove">
                                    {% csrf_token %}
                                </form>
                            </td>
                        </tr>
                        {% endwith %}
                    {% endfor %}
                    </tbody>
                </table>
                <div class="row float-right text-right">
                    <div class="col-md-6">
                        <h4>Total:</h4>
                        <h1>{{ cart.get_total_price }}$</h1>
                    </div>
                    <div class="col-md-6">
                        <p>
                            <a class="btn btn-primary" href="{% url 'home' %}" role="button" style="background-color:#906ab6; border-color: #432152;">Continue Shopping</a>
                            <a class="btn btn-primary" href="{% url 'cart:order' %}" role="button" style="background-color:#906ab6; border-color: #432152;">CheckOut</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <p class="text-center">Your cart is empty.</p>
        <p class="text-center">
            <a class="btn btn-primary" href="{% url 'home' %}" role="button" style="background-color:#906ab6; border-color: #432152;">Continue Shopping</a>
        </p>
    {% endif %}
{% endblock %}

c4Final/webshop/cart/templates/cart/order_confirm.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
    <h1 class="text-center" style="color: #432152;">Your order is accepted</h1>
{% endblock %}

c4Final/webshop/cart/templates/cart/order_page.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}

<h1 class="text-center" style="color: #432152;">Your contact details</h1>
<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<!-- Masked Input from CDN -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js"></script>


<form method="post" action="{% url 'cart:orderconf' %}" class="mx-auto" style="max-width: 900px;">
    {% csrf_token %}

    {% for field, errors in form.errors.items %}
        {% for error in errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}

    <div class="mb-4">
        <label for="form2Example1" class="form-label">Name</label>
        <input type="text" id="form2Example1" class="form-control" name="name" />
    </div>
  
    <div class="mb-4">
        <label for="form2Example2" class="form-label">Email</label>
        <input type="email" id="form2Example2" class="form-control" name="email" />
    </div>

    <div class="mb-4">
        {% if cart %}
        <p class="mb-5 text-center">
            <i class="text-info font-weight-bold"></i></p>
            <table class="table table-primary table-striped">
            <thead>
                <tr>
                    <th style="width:30%">Product</th>
                    <th style="width:12%">Price per unit</th>
                    <th style="width:10%">Quantity</th>
                    <th style="width:12%">Price</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                    {% with product=item.product %}
                        <tr>
                            <td data-th="Product">
                                <div class="row">
                                    <div class="col-md-9 text-left mt-sm-2">
                                        <h5>{{ product.name }}</h5>
                                    </div>
                                </div>
                            </td>
                            <td class="num">{{ item.price }}$</td>  
                                <td data-th="Quantity">
                                    <div class="col-md-9 text-left mt-sm-2">
                                        {{ item.quantity }}
                                    </div>  
                                </td>
                                <td class="num">{{ item.total_price }}$</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                </tbody>
            {% endif %}  
            </table>
    </div>

    <div class="col-md-6">
        <h4>Total:</h4>
        <h1>{{ cart.get_total_price }}$  <button type="submit" class="btn btn-primary btn-block" style="background-color:#906ab6; border-color: #432152;">Pay</button></h1>
    </div>
</form>

{% endblock %}